# Generated by Django 3.1.5 on 2021-01-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('manufacturing', models.IntegerField(max_length=500)),
                #('image', models.ImageField(null=True, blank= True,upload_to= 'images')),
                ('expired', models.IntegerField(default=0)),
            ],
        ),
    ]
