# Generated by Django 3.1.5 on 2021-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expired',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='manufacturing',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
